### ISSUE TITLE
URLs are case sensitive 

### ISSUE THREAD

**Issue by samdish** [IEEEDTU/TechWeek-2015#8]
http://techweek.dcetech.com/#designing
If in the above link I replace #designing with #Designing, the link won't work and would redirect me to the home page. 
I don't think there is a need for URLs to be case sensitive.

**Comment by sakshamsaxena** [comment]
Thanks for reporting! We'll fix it asap

**Comment by sakshamsaxena** [comment]
Fixed in 8e956ed
