### ISSUE TITLE
hashtags not working

### ISSUE THREAD

**Issue by prempalsingh** [IEEEDTU/TechWeek-2015#9]
Hashtags don't work unless you refresh the entire webpage. I am using Firefox on Ubuntu if that might help.

**Comment by h-chauhan** [comment]
That's about the working of browser. When you make changes to the URL of an open page, you have to refresh the page to see the effect. The hashtags were designed to redirect you to an event page directly from an email, message or social media. E.g. If you visit www.techweek.dcetech.com#designing from here, it will directly lead you to the Graphic Designing event, no need for refreshing. :)
Or else if you want to visit a particular event from the website, you can schedule section which will also directly lead you there without refreshing.

**Comment by sakshamsaxena** [comment]
@prempalsingh 
Hey, thanks for bringing this issue to our attention. Our linking system is a pseudo method for replacing internal linking, and it may not work as is in some browsers/environments. I think in Firefox different internal links on the same page are accessed without reloading the entire page or DOM.
We'll try to rectify this issue asap!

**Comment by sakshamsaxena** [comment]
@hchauhan1404
Try to replicate this error in Firefox. Maybe we need to make the linking global and attach to a new event. I'll comment further on it soon.

**Comment by sakshamsaxena** [comment]
Sadly, this is something which is beyond the scope of currently applied methods to produce hashtag linking. Had we used URL routing then this issue wouldn't have arisen at all, but I believe that very few percent of users would actually manually change the hash, when there are navigation buttons and a schedule slider already available.
